<?php
namespace Model;

class Admin implements IEAdmin {

    /*
     * Autogenerated by db
     * :number
     * */
    private string $id;

    /*
     * :string
     * */
    private string $lastname;


    /*
     * :string
     * */
    private string $firstname;

    /*
     * :string
     * */
    private string $mail ;

    /*
     * :string
     * */
    private string $password;

    /**
     * Admin constructor.
     * @param $id
     * @param $lastname
     * @param $firstname
     * @param $mail
     * @param $password
     */
    public function __construct($id, $lastname, $firstname, $mail, $password)
    {
        $this->id = $id;
        $this->lastname = $lastname;
        $this->firstname = $firstname;
        $this->mail = $mail;
        $this->password = $password;
    }

    public function getPassword() {
        return $this->password;
    }

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * @return string
     */
    public function getMail()
    {
        return $this->mail;
    }


}