<?php
namespace Model;

class User implements IEUser{

    /*
     * Autogenerated by db
     * :number
     * */
    private string $id;

    /*
     * :string
     * */
    private string $lastname;


    /*
     * :string
     * */
    private string $firstname;

    /*
     * :string
     * */
    private string $mail ;

    /*
     * :string
     * */
    private string $password;

    /**
     * :string
     * */
    private string $birth_date;

    /**
     * :string
     * */
    private string $adress;

    /**
     * Admin constructor.
     * @param $id
     * @param $lastname
     * @param $firstname
     * @param $mail
     * @param $password
     * @param $birth_date
     * @param $adress
     */
    public function __construct($id, $lastname, $firstname, $mail, $password, $birth_date, $adress)
    {
        $this->id = $id;
        $this->lastname = $lastname;
        $this->firstname = $firstname;
        $this->mail = $mail;
        $this->password = $password;
        $this->birth_date = $birth_date;
        $this->adress = $adress;
    }


    /**
     * @return hashed string 
     */
    public function getPassword() {
        return $this->password;
    }

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * @return string
     */
    public function getMail()
    {
        return $this->mail;
    }

    /**
     * @return string
     */ 
    public function getBirth_date()
    {
        return $this->birth_date;
    }

    /**
     * @return string
     */ 
    public function getAdress()
    {
        return $this->adress;
    }
}