<?php
namespace Model;

class AdminModel extends Model {

    /*
     * Autogenerated by db
     * :number
     * */
    private $id;

    /*
     * :string
     * */
    private $lastname;

    /*
     * :string
     * */
    private $firstname;

    /*
     * :string
     * */
    private $mail;

    /*
     * :string
     * */
    private $password;

    public function __construct($lastname, $firstname, $mail, $password)
    {
        $this->lastname = $lastname;
        $this->firstname = $firstname;
        $this->mail = $mail;
        $this->password = $password;
    }

    public function save() {

        $this->db->prepare(
            "INSERT INTO admin (firstname, lastname, mail, password) VALUES (:firstname, :lastname, :mail, :password)"
        );

        $req = $this->db->execute([
            "lastname" =>$this->lastname,
            "firstname" =>$this->firstname,
            "mail"=>$this->mail,
            "password"=>$this->password
        ]);

        if(!$req) {
            throw new \Exception(ERROR_SAVING_BDD);
        }

        return true;
    }

    public static function find() {
        self::find();
        //find admin according variable keys
    }

}